name: "wobbs"
mode: "release"
host: localhost
port: 8081
version: "v0.0.1"
snowflake:
  start_time: "2023-01-01"
  machine_id: 1

auth:
  jwt_expire: 8760

log:
  model: "dev"
  level: "info"
  filename: "app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: localhost
  port: 3308
  username: root
  password: root
  database: "wobbs"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: 116.62.108.144
  port: 6379
  password: redis
  database: 5
  pool_size: 100